# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    porcelain::porcelain_endpoint$new(
      "GET",
      "/add/<a:int>/<b:int>",
      add,
      returning = porcelain::porcelain_returning_json("numeric"))
  )
}
