#!/usr/bin/env bash
set -exu
HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       --build-arg GIT_ID=$GIT_SHA \
       --build-arg GIT_BRANCH=$GIT_BRANCH \
       --build-arg DETTL_VERSION=$PKG_VERSION \
       --tag $TAG_SHA \
       --tag $TAG_BRANCH \
       --tag $TAG_VERSION \
       -f docker/Dockerfile \
       .
