#!/usr/bin/env bash
set -exu
HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       --tag $TAG_SHA \
       --tag $TAG_BRANCH \
       --tag $TAG_VERSION \
       -f docker/Dockerfile \
       .
