## The typical approach here would be to make roxygen2 a hard
## dependency, import either the whole package or the three generics
## (roxy_tag_parse, roclet_process and roclet_output) then register
## the S3 methods with '@export' as normal.  However, this requires
## that we have roxygen2 available at runtime which is pretty weird
## given we only need it when running the package. From R 3.6.0 we can
## use the syntax below to register the methods when roxygen2 is
## loaded, which requires that we inject some raw content into the
## namespace (see R-exts).  Each of these is above the method used so
## we provide the minimum NAMESPACE support.

##' A roclet for processing `@porcelain` tags within a package. This
##' presents an automated declarative approach to defining porcelain
##' APIs using roxygen tags. When you roxygenise your package (e.g.,
##' with `devtools::document()` or `roxygen2::roxygenise()`) this
##' roclet will create a file `R/porcelain.R` within your package that
##' will be included into your package API.
##'
##' @title Define API using roxygen tags
##'
##' @return A roclet, used by `roxygen2` (not typically called by
##'   users directly)
##'
##' @export
porcelain_roclet <- function() {
  roxygen2::roclet("porcelain")
}


package_endpoints <- function(package) {
  fn <- getNamespace(package)[["__porcelain__"]]
  if (is.null(fn)) {
    ## TODO: diagnose the issue here:
    ## * DESCRIPTION does not contain roclet command
    ## * Need to redocument
    stop("Did not find package endpoints")
  }
  fn()
}


porcelain_package_endpoint <- function(package, method, path, state = NULL) {
  endpoint <- package_endpoints(package)[[paste(method, path)]]
  if (is.null(endpoint)) {
    stop(sprintf(
      "Did not find roxygen-based endpoint '%s %s' in package '%s'",
      method, path, package))
  }
  endpoint(state)
}


##' @rawNamespace S3method(roxygen2::roxy_tag_parse, roxy_tag_porcelain)
roxy_tag_parse.roxy_tag_porcelain <- function(x) {
  ## See roxygen_parse.R for the bulk of the implementation.
  x$val <- roxy_parse_string(x$raw, x$file, x$line)
  x
}


##' @rawNamespace S3method(roxygen2::roclet_process, roclet_porcelain)
roclet_process.roclet_porcelain <- function(x, blocks, env, base_path) {
  results <- list()
  message("Adding porcelain endpoints:")

  for (block in blocks) {
    tags <- roxygen2::block_get_tags(block, "porcelain")
    if (length(tags) > 1L) {
      found <- vcapply(tags, function(x)
        sprintf("%s:%d", basename(x$file), x$line))
      stop("More than one @porcelain block found for single function: ",
           paste(found, collapse = ", "))
    }
    if (length(tags) == 1L) {
      ## TODO: nice validation on these
      stopifnot(
        length(tags) == 1,
        is.function(block$object$value))
      endpoint <- roxy_process(tags[[1]], block$object$alias, env)
      results <- c(results, list(endpoint))
    }
  }

  if (length(results) == 0) {
    stop("Package contains no '@porcelain' tags")
  }

  c("`__porcelain__` <- function() {",
    paste0("  ", list_call("list", results)),
    "}")
}


roxy_process <- function(tag, target, env) {
  if (!is.function(env[[target]])) {
    stop("Target is not a function")
  }
  method <- tag$val$method
  path <- tag$val$path
  message(sprintf("- %s %s (%s:%d)", method, path,
                  basename(tag$file), tag$line))

  inputs <- roxy_process_inputs(tag$val$inputs, env, tag)
  returning <- roxy_process_returning(tag$val$returning, env, tag)

  args <- c(
    list(dquote(tag$val$method), dquote(tag$val$path), target),
    inputs,
    list(sprintf("returning = %s", returning)))

  create <- list_call("porcelain::porcelain_endpoint$new", args)

  ## Then we can test this:
  tryCatch(
    eval(parse(text = create), new.env(parent = env)),
    error = function(e) browser())

  ## Each endpoint gets wrapped in an anonymous function so that
  ## we can call them later at will, rebinding state etc.
  c(sprintf('"%s %s" = function(state) {', method, path),
    paste0("  ", create),
    "}")
}


##' @rawNamespace S3method(roxygen2::roclet_output, roclet_porcelain)
roclet_output.roclet_porcelain <- function(x, results, base_path, ...) {
  header <- "# Generated by porcelain: do not edit by hand"

  dest <- file.path(base_path, "R", "porcelain.R")
  if (file.exists(dest)) {
    prev <- readLines(dest)
    if (length(prev) > 0 && prev[[1]] != header) {
      ## TODO: better, actionable, error
      stop("porcelain.R is not ours to change")
    }
  }

  writeLines(c(header, results), dest)

  invisible(NULL)
}


roxy_error <- function(msg, x) {
  if (!is.null(x)) {
    msg <- paste(msg,
                 sprintf("  (while processing %s:%d)", x$file, x$line),
                 sep = "\n")
  }
  stop(msg)
}


roxy_process_inputs <- function(inputs, env, x) {
  stopifnot(names(inputs) == "query") # TODO: more generalisation needed

  ## TODO: validation on query - args must be simple list
  query_type <- unname(vcapply(inputs$query, function(x) x[[1]]))
  query <- paste(sprintf('%s = "%s"', names(inputs$query), query_type),
                 collapse = ", ")
  list(sprintf("porcelain::porcelain_input_query(%s)", query))
}


roxy_process_returning <- function(returning, env, x) {
  map <- c(
    json = "porcelain::porcelain_returning_json",
    binary = "porcelain::porcelain_returning_binary",
    generic = "porcelain::porcelain_returning")
  fn <- returning[[1]]
  if (fn %in% names(map)) {
    fn <- map[[fn]]
  } else if (grepl("::", fn)) {
    fn <- fn
  } else if (!is.null(exists(fn, env, mode = "function"))) {
    fn <- fn
  } else {
    stop(sprintf("Did not find returning function '%s'", fn))
  }

  args <- paste(vcapply(returning[-1], deparse), collapse = ", ")
  sprintf("%s(%s)", fn, args)
}
